version: '3.1'
services:
  app:
    image: node:18-slim@sha256:0a621cdd7d66ad8976f4246ab0661e3b1dd0d397c1dd784ea01bf740bd1c2522
    platform: linux/amd64
    working_dir: /app
    ports:
      - '4029:4029'
    volumes:
      - ./:/app
    environment:
      - NODE_ENV=development
    command: "bash -c 'cd /app && npm run start:dev'"
