#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npm test
npm run test-integrations
echo "running lint-fix in: $(pwd)"
npm run lint-fix
cd .aws
echo "running lint-fix in: $(pwd)"
npm run lint-fix
